name: Check

on:
  workflow_dispatch: ~
  push:
    branches: ['*.x']
  pull_request: ~

jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: task composer-validate composer-check-require

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: task lint -- --format=checkstyle

  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-versions: [lowest, highest]
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
          dependency-versions: ${{ matrix.dependency-versions }}
      - run: task psalm -- --php-version=${{ matrix.php }} --stats --output-format=github

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: task phpstan

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
        dependency-versions: [lowest, highest]
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-file: development
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
          dependency-versions: ${{ matrix.dependency-versions }}
      - run: task test -- --colors=always

  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: NAME=Reflection task check-package
        env:
          COMPOSER_ROOT_VERSION: 0.4-dev
